name: fhe_template
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=2.18.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.1.0
  json_annotation: ^4.7.0
  firebase_core: ^1.23.0
  firebase_auth: ^3.10.0
  firebase_messaging: ^13.0.3
  cloud_firestore: ^3.4.9
  dio: ^4.0.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.1
  freezed: ^2.1.1
  json_serializable: ^6.4.0
flutter:
  uses-material-design: true
